/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestCountdownRouteImport } from './routes/test-countdown'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportResolveRouteImport } from './routes/support-resolve'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SpectateRouteImport } from './routes/spectate'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MatchHistoryRouteImport } from './routes/match-history'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GameRouteImport } from './routes/game'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AiGameRouteImport } from './routes/ai-game'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'

const TestCountdownRoute = TestCountdownRouteImport.update({
  id: '/test-countdown',
  path: '/test-countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportResolveRoute = SupportResolveRouteImport.update({
  id: '/support-resolve',
  path: '/support-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateRoute = SpectateRouteImport.update({
  id: '/spectate',
  path: '/spectate',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchHistoryRoute = MatchHistoryRouteImport.update({
  id: '/match-history',
  path: '/match-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGameRoute = AiGameRouteImport.update({
  id: '/ai-game',
  path: '/ai-game',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-game': typeof AiGameRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/match-history': typeof MatchHistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/spectate': typeof SpectateRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/support-resolve': typeof SupportResolveRoute
  '/terms': typeof TermsRoute
  '/test-countdown': typeof TestCountdownRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/achievements': typeof AchievementsRoute
  '/ai-game': typeof AiGameRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/match-history': typeof MatchHistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/spectate': typeof SpectateRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/support-resolve': typeof SupportResolveRoute
  '/terms': typeof TermsRoute
  '/test-countdown': typeof TestCountdownRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-game': typeof AiGameRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/maintenance': typeof MaintenanceRoute
  '/match-history': typeof MatchHistoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/spectate': typeof SpectateRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/support-resolve': typeof SupportResolveRoute
  '/terms': typeof TermsRoute
  '/test-countdown': typeof TestCountdownRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/achievements'
    | '/admin'
    | '/ai-game'
    | '/announcements'
    | '/auth'
    | '/game'
    | '/leaderboard'
    | '/maintenance'
    | '/match-history'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/replay'
    | '/settings'
    | '/spectate'
    | '/subscription'
    | '/support'
    | '/support-resolve'
    | '/terms'
    | '/test-countdown'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/achievements'
    | '/ai-game'
    | '/announcements'
    | '/auth'
    | '/game'
    | '/leaderboard'
    | '/maintenance'
    | '/match-history'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/replay'
    | '/settings'
    | '/spectate'
    | '/subscription'
    | '/support'
    | '/support-resolve'
    | '/terms'
    | '/test-countdown'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/achievements'
    | '/admin'
    | '/ai-game'
    | '/announcements'
    | '/auth'
    | '/game'
    | '/leaderboard'
    | '/maintenance'
    | '/match-history'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/replay'
    | '/settings'
    | '/spectate'
    | '/subscription'
    | '/support'
    | '/support-resolve'
    | '/terms'
    | '/test-countdown'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiGameRoute: typeof AiGameRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  GameRoute: typeof GameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MatchHistoryRoute: typeof MatchHistoryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  SpectateRoute: typeof SpectateRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  SupportResolveRoute: typeof SupportResolveRoute
  TermsRoute: typeof TermsRoute
  TestCountdownRoute: typeof TestCountdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-countdown': {
      id: '/test-countdown'
      path: '/test-countdown'
      fullPath: '/test-countdown'
      preLoaderRoute: typeof TestCountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-resolve': {
      id: '/support-resolve'
      path: '/support-resolve'
      fullPath: '/support-resolve'
      preLoaderRoute: typeof SupportResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate': {
      id: '/spectate'
      path: '/spectate'
      fullPath: '/spectate'
      preLoaderRoute: typeof SpectateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-history': {
      id: '/match-history'
      path: '/match-history'
      fullPath: '/match-history'
      preLoaderRoute: typeof MatchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-game': {
      id: '/ai-game'
      path: '/ai-game'
      fullPath: '/ai-game'
      preLoaderRoute: typeof AiGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AiGameRoute: AiGameRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  GameRoute: GameRoute,
  LeaderboardRoute: LeaderboardRoute,
  MaintenanceRoute: MaintenanceRoute,
  MatchHistoryRoute: MatchHistoryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  SpectateRoute: SpectateRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  SupportResolveRoute: SupportResolveRoute,
  TermsRoute: TermsRoute,
  TestCountdownRoute: TestCountdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
